import numpy as np

class AcousticArrayController:
    def __init__(self, num_elements=1024, radius_mm=100.0, c_medium=1540.0):
        """
        Initializes a hemispherical phased-array configuration.
        
        Parameters:
        - num_elements: Total number of ultrasound actuators (default 1024).
        - radius_mm: The curvature radius of the helmet/array shell in millimeters.
        - c_medium: Speed of sound in the hydrogel matrix (default 1540 m/s).
        """
        self.num_elements = num_elements
        self.radius = radius_mm / 1000.0  # Convert to meters
        self.c = c_medium                 # Meters per second
        self.actuator_positions = self._generate_hemisphere_grid()

    def _generate_hemisphere_grid(self):
        """Mathematically distributes 1,024 actuators evenly across a hemisphere surface."""
        positions = []
        indices = np.arange(0, self.num_elements, dtype=float) + 0.5
        phi = np.arccos(1 - indices / self.num_elements) / 2.0  # Limit to upper hemisphere
        theta = np.pi * (1 + 5**0.5) * indices                  # Golden ratio spiral distribution
        
        x = self.radius * np.sin(phi) * np.cos(theta)
        y = self.radius * np.sin(phi) * np.sin(theta)
        z = self.radius * np.cos(phi)
        
        return np.column_stack((x, y, z))

    def calculate_phase_delays(self, target_coord_mm):
        """
        Calculates the exact time delays (in microseconds) required for each 
        actuator to focus constructive acoustic energy at a specific 3D coordinate.
        """
        # Convert target coordinates from mm grid to meters relative to array center
        target_m = np.array(target_coord_mm) / 1000.0
        
        # Calculate Euclidean distance from every single actuator to the target coordinate
        distances = np.linalg.norm(self.actuator_positions - target_m, axis=1)
        
        # Time of flight from each actuator to the target point
        times_of_flight = distances / self.c
        
        # To focus energy, the furthest actuators must fire first. 
        # Delay time = Max Time of Flight - Individual Time of Flight
        max_tof = np.max(times_of_flight)
        time_delays_sec = max_tof - times_of_flight
        
        # Convert to microseconds for hardware digitizer precision
        time_delays_us = time_delays_sec * 1e6
        
        return time_delays_us

# =====================================================================
# SYSTEM VERIFICATION TEST (Validating Real-Time Phase Steering)
# =====================================================================
if __name__ == "__main__":
    print("[1/2] Initializing 1024-element Hemispherical Phased Array Matrix...")
    controller = AcousticArrayController(num_elements=1024, radius_mm=100.0)
    
    # Let's pull the next coordinate path target generated by our router script
    next_routing_node = (10, 10, 10) # 3D coordinate in mm inside the gel matrix
    
    print(f"[2/2] Calculating phase delay profile for target coordinate: {next_routing_node} mm")
    delays = controller.calculate_phase_delays(next_routing_node)
    
    print("\n================ HARDWARE PHASE GRID REPORT ================")
    print(f"Total Configured Actuators Checked: {len(delays)} / 1024 Channels")
    print(f"Maximum Delay Required (Earliest Channel Fired): {np.max(delays):.3f} \u03bcs")
    print(f"Minimum Delay Required (Latest Channel Fired)  : {np.min(delays):.3f} \u03bcs")
    print(f"Channel 0 Phase Setting Transmitted           : {delays[0]:.3f} \u03bcs")
    print("============================================================")
    print("-> Hardware State: Phase matrix locked. Ready to compress wave fronts.")